### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by scientes** [wiltonsr/Trello2Kanboard#3]
would it be possible to make this script work under windows?

```bash
trello2kanboard --json-file C:\Path\proj1.json import --api-url  https://url/jsonrpc.php --api-user jsonrpc --api-token token5 --project-owner user
User user- user successfully connected.
Der Befehl "stty" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.  (command stty not found)
ValueError('not enough values to unpack (expected 2, got 0)')
````
my guess would be https://github.com/wiltonsr/Trello2Kanboard/blob/e321f909073895a78eb8f6d0956f9e45fd5333a5/trello2kanboard/commands/utils.py#L12

is the problem but i haven't looked to deep into this

**Comment by wiltonsr** [comment]
Hi, thanks for using `Trello2Kanboard`. 

Unfortunately, I have no time to continue maintaining this project. 
But contributions are always welcome.
